### ISSUE TITLE
Employee Page: Mission Statement

### ISSUE THREAD

**Issue by morecallan** [nss-evening-cohort-7/dating-site-instructorz#6]
# Story
As a user, in order to know what the site is about, I should be able to see a mission statement on the employees page.

# Acceptance Criteria
**When** A plastic dino looks at employees page
**Then** a plastic dino should see a mission statement

# Technical Notes
- We need to be able to link to this employee page from the homepage, if no nav is done, then add an href in the index.html

**Comment by zoeames** [comment]
Wireframe:

![image](https://user-images.githubusercontent.com/8093647/37242648-c6530eec-2432-11e8-99f8-9a42dc792b48.png)
