### ISSUE TITLE
Local Dinos: List All Dinos

### ISSUE THREAD

**Issue by rousell** [nss-evening-cohort-7/dating-site-instructorz#7]
# Story
As a user, when I navigate to the local dinos page, I would like to see all dinos in the area.

# Acceptance Criteria
**When** the user navigates to the local dinos page
**Then** they should see all the dinos

# Technical Notes
- Add and/or modify local_dinos.html file
- Create dinoStringBuilder which loops over dinos array
- Display dinos using printToDom function

**Comment by zoeames** [comment]
Wireframe:
![image](https://user-images.githubusercontent.com/8093647/37242729-fe673c4e-2433-11e8-9cfb-599d229974f3.png)
